version: '3'
services:

  app:
    # build: .
    # volumes:
    #   - ./src:/app
    #   - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    # working_dir: /app/main
    # env_file:
    #   - .env
    # ports:
    #   - 8080:8080

    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app
    working_dir: /app
      
    # image: golang:1.14.2-alpine
    # volumes:
    #   - .:/go/jenny_canasta
    # working_dir: /go/jenny_canasta/main
    # command: go run main.go
    # links: 
    #   - postgres

  # postgres:
  #   image: postgres
  #   restart: always
  #   environment: 
  #     POSTGRES_PASSWORD: example